# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0003_auto_20180411_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 19, 30, 16, 39257)),
        ),
    ]
