# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0004_auto_20180411_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.CharField(default=100, max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 19, 32, 37, 764649)),
        ),
    ]
