# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0007_auto_20180411_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 20, 1, 5, 969250)),
        ),
    ]
