# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0008_auto_20180411_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 5, 12, 25, 378558)),
        ),
    ]
