# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 07:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talkingtree', '0009_auto_20180412_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvoteanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=None)),
            ],
            options={
                'ordering': ['-upvote'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 30, 2, 297065)),
        ),
        migrations.AddField(
            model_name='upvoteanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkingtree.Answer'),
        ),
        migrations.AddField(
            model_name='upvoteanswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
