# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0010_auto_20180412_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 58, 28, 546460)),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
    ]
