# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0013_auto_20180412_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 10, 33, 33, 482362)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 10, 33, 33, 483880)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 10, 33, 33, 481532)),
        ),
    ]
