# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingtree', '0016_auto_20180413_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 6, 56, 51, 849464)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 6, 56, 51, 850870)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 6, 56, 51, 848709)),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='upvote',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='upvotecomment',
            name='upvote',
            field=models.NullBooleanField(default=None),
        ),
    ]
